[package]
name = "lettuce-magician/min"
description = "minimal and simple UI library"
version = "1.1.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["sourcemap.json","README.md","selene.toml","pack.project.json","default.project.json","Min.rbxm","bundle.darklua.json","test"]

[dependencies]
